export const roadmapNodes = [
  {
    id: "1",
    type: "custom",
    position: { x: 0, y: 0 },
    data: { label: "Arrays and Hashing", type: "source" },
    draggable: false,
  },
  {
    id: "2",
    type: "custom",
    position: { x: -100, y: 100 },
    data: { label: "Two Pointers", type: "both" },
    draggable: false,
  },
  {
    id: "3",
    type: "custom",
    position: { x: 100, y: 100 },
    data: { label: "Stack", type: "target" },
    draggable: false,
  },
  {
    id: "4",
    type: "custom",
    position: { x: -200, y: 200 },
    data: { label: "Binary Search", type: "both" },
    draggable: false,
  },
  {
    id: "5",
    type: "custom",
    position: { x: 0, y: 200 },
    data: { label: "Sliding Window", type: "target" },
    draggable: false,
  },
  {
    id: "6",
    type: "custom",
    position: { x: 200, y: 200 },
    data: { label: "Linked List", type: "both" },
    draggable: false,
  },
  {
    id: "7",
    type: "custom",
    position: { x: -100, y: 300 },
    data: { label: "Trees", type: "both" },
    draggable: false,
  },
  {
    id: "8",
    type: "custom",
    position: { x: -200, y: 400 },
    data: { label: "Tries", type: "both" },
    draggable: false,
  },
  {
    id: "9",
    type: "custom",
    position: { x: 200, y: 400 },
    data: { label: "Backtracking", type: "both" },
    draggable: false,
  },
  {
    id: "10",
    type: "custom",
    position: { x: -300, y: 500 },
    data: { label: "Heap / Priority Queue", type: "both" },
    draggable: false,
  },
  {
    id: "11",
    type: "custom",
    position: { x: 100, y: 500 },
    data: { label: "Graphs", type: "both" },
    draggable: false,
  },
  {
    id: "12",
    type: "custom",
    position: { x: 450, y: 500 },
    data: { label: "1-D DP", type: "both" },
    draggable: false,
  },
  {
    id: "13",
    type: "custom",
    position: { x: -400, y: 600 },
    data: { label: "Intervals", type: "target" },
    draggable: false,
  },
  {
    id: "14",
    type: "custom",
    position: { x: -200, y: 600 },
    data: { label: "Greedy", type: "target" },
    draggable: false,
  },
  {
    id: "15",
    type: "custom",
    position: { x: 0, y: 600 },
    data: { label: "Advanced Graphs", type: "target" },
    draggable: false,
  },
  {
    id: "16",
    type: "custom",
    position: { x: 300, y: 600 },
    data: { label: "2-D DP", type: "target" },
    draggable: false,
  },
  {
    id: "17",
    type: "custom",
    position: { x: 500, y: 600 },
    data: { label: "Bit Manipulation", type: "both" },
    draggable: false,
  },
  {
    id: "18",
    type: "custom",
    position: { x: 200, y: 700 },
    data: { label: "Math & Geometry", type: "target" },
    draggable: false,
  },
];
